# Generated by Django 2.2.2 on 2019-08-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='click_num',
            new_name='click_nums',
        ),
    ]
