# Generated by Django 2.2.2 on 2019-08-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_coursecomments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.IntegerField(verbose_name='手机号'),
        ),
    ]
